/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/bues/account/init': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 初始化账户 */
    post: operations['\u521D\u59CB\u5316\u8D26\u6237'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/account/update': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 更新账户信息 */
    post: operations['\u66F4\u65B0\u8D26\u6237\u4FE1\u606F'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/account/my-invite': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 获取我的邀请列表 */
    post: operations['\u83B7\u53D6\u6211\u7684\u9080\u8BF7\u5217\u8868'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/application/restore/:applicationId': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 恢复已删除的应用 */
    post: operations['\u6062\u590D\u5DF2\u5220\u9664\u7684\u5E94\u7528'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/application/trash/:projectId': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 查询垃圾桶中的应用 */
    get: operations['\u67E5\u8BE2\u5783\u573E\u6876\u4E2D\u7684\u5E94\u7528'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/application/delete/:applicationId': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 删除应用 */
    post: operations['\u5220\u9664\u5E94\u7528'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/application/list/:projectId': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 查询应用列表 */
    get: operations['\u67E5\u8BE2\u5E94\u7528\u5217\u8868'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/application/update': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 更新应用 */
    post: operations['\u66F4\u65B0\u5E94\u7528'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/application/create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 创建应用 */
    post: operations['\u521B\u5EFA\u5E94\u7528'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/environment-variable/list/:projectId': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取项目的环境变量列表 */
    get: operations['\u83B7\u53D6\u9879\u76EE\u7684\u73AF\u5883\u53D8\u91CF\u5217\u8868'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/environment-variable/delete/:id': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 删除环境变量 */
    post: operations['\u5220\u9664\u73AF\u5883\u53D8\u91CF'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/environment-variable/update': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 更新环境变量 */
    post: operations['\u66F4\u65B0\u73AF\u5883\u53D8\u91CF'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/environment-variable/create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 创建环境变量 */
    post: operations['\u521B\u5EFA\u73AF\u5883\u53D8\u91CF'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/interface-version-change/submit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 提交应用变更信息 */
    post: operations['\u63D0\u4EA4\u5E94\u7528\u53D8\u66F4\u4FE1\u606F'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/project/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 查询项目列表 */
    get: operations['\u67E5\u8BE2\u9879\u76EE\u5217\u8868'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/project/:projectId': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 查询项目 */
    get: operations['\u67E5\u8BE2\u9879\u76EE'];
    put?: never;
    post?: never;
    /** 删除项目 */
    delete: operations['\u5220\u9664\u9879\u76EE'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/project/create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 创建项目 */
    post: operations['qqqqq'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/project/update': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 更新项目 */
    post: operations['\u66F4\u65B0\u9879\u76EE'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/project/invite': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 邀请用户加入项目 */
    post: operations['\u9080\u8BF7\u7528\u6237\u52A0\u5165\u9879\u76EE'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/project/accept-invite/:id': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 接受项目邀请 */
    post: operations['\u63A5\u53D7\u9879\u76EE\u9080\u8BF7'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/edge/s3/avatar-upload-url': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 头像上传签名 URL */
    get: operations['\u5934\u50CF\u4E0A\u4F20\u7B7E\u540D URL'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  '\u521D\u59CB\u5316\u8D26\u6237': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: Record<string, never>;
          };
        };
      };
    };
  };
  '\u66F4\u65B0\u8D26\u6237\u4FE1\u606F': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': {
          username: string;
          avatar_url: string | null;
        };
      };
    };
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: Record<string, never>;
          };
        };
      };
    };
  };
  '\u83B7\u53D6\u6211\u7684\u9080\u8BF7\u5217\u8868': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: {
              list: unknown;
            };
          };
        };
      };
    };
  };
  '\u6062\u590D\u5DF2\u5220\u9664\u7684\u5E94\u7528': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        params: {
          applicationId: string;
        };
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: Record<string, never>;
          };
        };
      };
    };
  };
  '\u67E5\u8BE2\u5783\u573E\u6876\u4E2D\u7684\u5E94\u7528': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        params: {
          projectId: string;
        };
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: {
              [key: string]: unknown;
            }[];
          };
        };
      };
    };
  };
  '\u5220\u9664\u5E94\u7528': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        params: {
          applicationId: string;
        };
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: Record<string, never>;
          };
        };
      };
    };
  };
  '\u67E5\u8BE2\u5E94\u7528\u5217\u8868': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        params: {
          projectId: string;
        };
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: {
              [key: string]: unknown;
            }[];
          };
        };
      };
    };
  };
  '\u66F4\u65B0\u5E94\u7528': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': {
          name: string;
          description: string | null;
          id?: string | unknown;
        };
      };
    };
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: Record<string, never>;
          };
        };
      };
    };
  };
  '\u521B\u5EFA\u5E94\u7528': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': {
          project_id: string;
          name: string;
          description: string | null;
        };
      };
    };
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: Record<string, never>;
          };
        };
      };
    };
  };
  '\u83B7\u53D6\u9879\u76EE\u7684\u73AF\u5883\u53D8\u91CF\u5217\u8868': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        params: {
          projectId: string;
        };
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: Record<string, never>[];
          };
        };
      };
    };
  };
  '\u5220\u9664\u73AF\u5883\u53D8\u91CF': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        params: {
          id: string;
        };
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: Record<string, never>;
          };
        };
      };
    };
  };
  '\u66F4\u65B0\u73AF\u5883\u53D8\u91CF': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': {
          value: string;
          name: string;
          format: 'env' | 'json' | 'yaml';
          id?: string | unknown;
        };
      };
    };
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: Record<string, never>;
          };
        };
      };
    };
  };
  '\u521B\u5EFA\u73AF\u5883\u53D8\u91CF': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': {
          project_id: string;
          value: string;
          name: string;
          format: 'env' | 'json' | 'yaml';
          application_id?: string | null | unknown;
        };
      };
    };
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: Record<string, never>;
          };
        };
      };
    };
  };
  '\u63D0\u4EA4\u5E94\u7528\u53D8\u66F4\u4FE1\u606F': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': {
          application_id: string;
          change_details?: unknown;
        };
      };
    };
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: Record<string, never>;
          };
        };
      };
    };
  };
  '\u67E5\u8BE2\u9879\u76EE\u5217\u8868': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: unknown;
          };
        };
      };
    };
  };
  '\u67E5\u8BE2\u9879\u76EE': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        params: {
          projectId: string;
        };
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: Record<string, never>;
          };
        };
      };
    };
  };
  '\u5220\u9664\u9879\u76EE': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        params: {
          projectId: string;
        };
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: Record<string, never>;
          };
        };
      };
    };
  };
  qqqqq: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
          description: string | null;
          slug: string;
        };
      };
    };
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: Record<string, never>;
          };
        };
      };
    };
  };
  '\u66F4\u65B0\u9879\u76EE': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': {
          name: string;
          description: string | null;
          id?: string | unknown;
        };
      };
    };
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: Record<string, never>;
          };
        };
      };
    };
  };
  '\u9080\u8BF7\u7528\u6237\u52A0\u5165\u9879\u76EE': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': {
          project_id: string;
          email: string;
        };
      };
    };
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: Record<string, never>;
          };
        };
      };
    };
  };
  '\u63A5\u53D7\u9879\u76EE\u9080\u8BF7': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        params: {
          id: string;
        };
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: Record<string, never>;
          };
        };
      };
    };
  };
  '\u5934\u50CF\u4E0A\u4F20\u7B7E\u540D URL': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 请求成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            data: {
              url: string;
            };
          };
        };
      };
    };
  };
}
