/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/bues/account/init': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 初始化账户 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: Record<string, never>;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/account/update': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 更新账户信息 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            username: string;
            avatar_url: string | null;
          };
        };
      };
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: Record<string, never>;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/account/my-invite': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 获取我的邀请列表 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: {
                list: {
                  project_id: string;
                  id: string;
                  name: string | null;
                }[];
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/application/restore/:applicationId': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 恢复已删除的应用 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          params: {
            applicationId: string;
          };
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: Record<string, never>;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/application/trash/:projectId': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 查询垃圾桶中的应用 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          params: {
            projectId: string;
          };
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: {
                id: string;
                created_at: string;
                description: string | null;
                name: string;
                updated_at: string;
                version: number;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/application/delete/:applicationId': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 删除应用 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          params: {
            applicationId: string;
          };
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: Record<string, never>;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/application/list/:projectId': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 查询应用列表 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          params: {
            projectId: string;
          };
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: {
                id: string;
                created_at: string;
                description: string | null;
                name: string;
                updated_at: string;
                version: number;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/application/update': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 更新应用 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            description: string | null;
            name: string;
            id?: string | unknown;
          };
        };
      };
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: Record<string, never>;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/application/create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 创建应用 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            project_id: string;
            description: string | null;
            name: string;
          };
        };
      };
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: Record<string, never>;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/environment-variable/list/:projectId': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取项目的环境变量列表 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          params: {
            projectId: string;
          };
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: {
                project_id: string;
                deleted_flag: boolean | null;
                id: string;
                created_at: string | null;
                name: string;
                updated_at: string | null;
                value: string;
                format: components['schemas']['VariableFormat'];
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/environment-variable/delete/:id': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 删除环境变量 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          params: {
            id: string;
          };
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: Record<string, never>;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/environment-variable/update': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 更新环境变量 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            name: string;
            value: string;
            format: 'env' | 'json' | 'yaml';
            id?: string | unknown;
          };
        };
      };
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: Record<string, never>;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/environment-variable/create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 创建环境变量 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            project_id: string;
            name: string;
            value: string;
            format: 'env' | 'json' | 'yaml';
            application_id?: string | null | unknown;
          };
        };
      };
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: Record<string, never>;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/interface-version-change/submit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 提交应用变更信息 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            application_id: string;
            change_details?: unknown;
          };
        };
      };
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: Record<string, never>;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/project/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 查询项目列表 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: {
                id: string;
                created_at: string | null;
                description: string | null;
                max_applications: number | null;
                max_collaborators: number | null;
                name: string;
                slug: string;
                updated_at: string | null;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/project/:projectId': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 查询项目 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          params: {
            projectId: string;
          };
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: {
                deleted_flag: boolean | null;
                id: string;
                user_id: string;
                created_at: string | null;
                description: string | null;
                max_applications: number | null;
                max_collaborators: number | null;
                name: string;
                slug: string;
                updated_at: string | null;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** 删除项目 */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          params: {
            projectId: string;
          };
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: Record<string, never>;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/project/create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 创建项目 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            description: string | null;
            name: string;
            slug: string;
          };
        };
      };
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: Record<string, never>;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/project/update': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 更新项目 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            description: string | null;
            name: string;
            id?: string | unknown;
          };
        };
      };
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: Record<string, never>;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/project/invite': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 邀请用户加入项目 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            project_id: string;
            email: string;
          };
        };
      };
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: Record<string, never>;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bues/project/accept-invite/:id': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 接受项目邀请 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          params: {
            id: string;
          };
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: Record<string, never>;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/edge/s3/avatar-upload-url': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 头像上传签名 URL */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 请求成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
              data: {
                url: string;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    VariableFormat: 'env' | 'json' | 'yaml';
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
